clouds:
    from:
        type: os
        host: 172.18.172.35
        endpoint_glance: http://172.18.172.35:9292
        user: admin
        password: admin
        tenant: admin
        path_to_disk: /var/lib/nova/instances/%s/disk
    to:
        type: os
        host: 172.18.172.22
        endpoint_glance: http://172.18.172.22:9292
        user: admin
        password: admin
        tenant: admin
        path_to_disk: /var/lib/nova/instances/%s/disk
        import_rules:
            default: {}
            overwrite:
                key: {name: control}
                networks:
                 - name: "net04_ext"
key_filename:
    name: privkey
instances:
 - key_name: amazon
