clouds:
    from:
        type: os
        host: 172.18.172.35
        user: admin
        password: admin
        tenant: admin
    to:
        type: os
        host: 172.18.172.22
        user: admin
        password: admin
        tenant: admin
        import_rules:
            default: {}
            overwrite:
                key: {name: control}
                networks:
                 - name: "net04_ext"
        
instances:
 - key_name: amazon
