clouds:
    from:
        type: os
        host: 172.18.172.68
        user: admin
        password: admin
        tenant: admin
        ephemeral_drives:
          ceph: no
          convert_diff_file: qcow2
          convert_ephemeral_drive: qcow2
        cinder:
          backend: ceph
          disk_format: qcow2
        temp: /root/temp
    to:
        type: os
        host: 172.18.172.35
        user: admin
        password: admin
        tenant: admin
        temp: /root/merge
        mysql:
          user: root
          password:
        cinder:
          backend: iscsi
        glance:
          convert_to_raw: yes
        ephemeral_drives:
          ceph: no
        transfer_ephemeral:
          compress: gzip
          level_compress: 9
        transfer_file:
          compress: dd
          level_compress: 9
        import_rules:
            default: {}
            overwrite:
                key: {name: control}
                networks:
                 - name: "net04"
        speed_limit: 10MB
key_filename:
    name: privkey
instances:
 - key_name: control
