clouds:
    from:
        type: os
        host: 172.18.172.20
        user: admin
        password: admin
        tenant: admin
        ephemeral_drives:
          ceph: no
        cinder:
          backend: ceph
          disk_format: qcow2
    to:
        type: os
        host: 172.18.172.35
        user: admin
        password: admin
        tenant: admin
        temp: /root/merge
        cinder:
          backend: iscsi
        glance:
          convert_to_raw: yes
        ephemeral_drives:
          ceph: no
        transfer_ephemeral:
          compress: gzip
          level_compress: 9
        import_rules:
            default: {}
            overwrite:
                key: {name: control}
                networks:
                 - name: "net04"
key_filename:
    name: privkey
instances:
 - key_name: key
