clouds:
    from:
        type: os
        host: 172.18.172.43
        user: admin
        password: 37d3e39891914512
        tenant: admin
        cinder:
          disk_format: qcow2
    to:
        type: os
        host: 172.18.172.20
        user: admin
        password: admin
        tenant: admin
        temp: /root/merge
        glance:
          backend: ceph
        import_rules:
            default: {}
            overwrite:
                key: {name: control}
                networks:
                 - name: "net04"
key_filename:
    name: privkey
instances:
 - key_name: key
