clouds:
    from:
        type: os
        host: 172.18.172.73
        user: source-user-1
        password: migration
        tenant: source_proj-1
        ephemeral_drives:
          ceph: no
          convert_diff_file: qcow2
          convert_ephemeral_drive: qcow2
        cinder:
          backend: iscsi
          disk_format: qcow2
        temp: /root/temp
        identity:
          connection: mysql+mysqlconnector
        keep_user_passwords: no
    to:
        type: os
        host: 172.18.172.77
        user: dest-user-1
        password: migration
        tenant: dest-proj-1
        temp: /root/merge
        mysql:
          user: root
          password:
        cinder:
          backend: iscsi
        glance:
          convert_to_raw: yes
        ephemeral_drives:
          ceph: no
        transfer_ephemeral:
          compress: gzip
          level_compress: 9
        transfer_file:
          compress: dd
          level_compress: 9
        import_rules:
            default: {}
            overwrite:
                key: {name: dest-key-1}
                networks:
        keep_ip: no
        speed_limit: 10MB
        identity:
          connection: mysql+mysqlconnector
mail:
    mail_server: smtp.gmail.com:587
    username: dsozinov@mirantis.com
    password:
    from_addr: dsozinov@mirantis.com
key_filename:
    name: id_rsa
instances:
 - key_name: source-key-1
