clouds:
    source:
        type: os
        host: 172.18.172.106
        user: admin
        password: verybadpass
        tenant: admin
        ephemeral_drives:
          ceph: no
          convert_diff_file: qcow2
          convert_ephemeral_drive: qcow2
        cinder:
          backend: iscsi
          transfer_via_glance: no
          disk_format: qcow2
        temp: /root/temp
        identity:
          connection: mysql+mysqlconnector
        keep_user_passwords: no
        ssh_transfer_port: 9999
    destination:
        type: os
        host: 172.18.172.22
        user: admin
        password: admin
        tenant: admin
        temp: /root/merge
        mysql:
          user: root
          password:
        cinder:
          backend: iscsi
        glance:
          convert_to_raw: yes
        ephemeral_drives:
          ceph: no
        transfer_ephemeral:
          compression: gzip
          level_compression: 9
        transfer_file:
          compression: dd
          level_compression: 9
        import_rules:
            default: {}
            overwrite:
                key: {name: key}
                networks:
                 - name: "net04"
        keep_ip: no
        speed_limit: 10MB
        identity:
          connection: mysql+mysqlconnector

mail:
    mail_server: smtp.yandex.ru:25
    username: source-cloud-1@yandex.ru
    password: need_pass
    from_addr: source-cloud-1@yandex.ru
key_filename:
    name: id_rsa
instances:
 - key_name: mykey
