clouds:
    from:
        type: os
        host: 172.18.172.102
        user: admin
        password: admin
        tenant: admin
        ephemeral_drives:
          ceph: no
          convert_diff_file: qcow2
          convert_ephemeral_drive: qcow2
        cinder:
          backend: iscsi
          disk_format: qcow2
        temp: /root/temp
        identity:
          connection: mysql+mysqlconnector
        keep_user_passwords: no
        ssh_transfer_port: 9999
    to:
        type: os
        host: 172.18.172.77
        user: admin
        password: admin
        tenant: admin
        temp: /root/merge
        mysql:
          user: root
          password:
        cinder:
          backend: iscsi
        glance:
          convert_to_raw: yes
        ephemeral_drives:
          ceph: no
        transfer_ephemeral:
          compress: gzip
          level_compress: 9
        transfer_file:
          compress: dd
          level_compress: 9
        import_rules:
            default: {}
            overwrite:
                key: {name: dest-key-1}
                networks:
                 - name: "net04"
                 - name: "test-net"
        keep_ip: yes
        speed_limit: 10MB
        identity:
          connection: mysql+mysqlconnector

mail:
    mail_server: smtp.yandex.ru:25
    username: source-cloud-1@yandex.ru
    password: need_pass
    from_addr: source-cloud-1@yandex.ru
key_filename:
    name: id_rsa
instances:
 - key_name: source-key
