clouds:
    source:
        type: os
        host: 172.18.172.13
        apihost: 172.18.172.13
        user: admin
        password: admin
        tenant: admin
        ephemeral_drives:
          ceph: no
          convert_diff_file: qcow2
          convert_ephemeral_drive: qcow2
        cinder:
          backend: iscsi
          transfer_via_glance: no
          disk_format: qcow2
        temp: /root/temp
        identity:
          connection: mysql+mysqlconnector
        keep_user_passwords: no
        ssh_transfer_port: 9999
    destination:
        type: os
        host: 172.18.172.108
        apihost: 172.18.172.108
        user: admin
        password: admin
        tenant: admin
        temp: /root/merge
        mysql:
          user: root
          password:
        cinder:
          backend: iscsi
        glance:
          convert_to_raw: yes
        ephemeral_drives:
          ceph: no
        transfer_ephemeral:
          compression: gzip
          level_compression: 9
        transfer_file:
          compression: dd
          level_compression: 9
        import_rules:
            default: {}
            overwrite:
                key: {name: testpair}
                networks:
                 - name: "net04"
        keep_ip: yes
        speed_limit: 10MB
        identity:
          connection: mysql+mysqlconnector
mail:
    mail_server: <server:port>
    username: <user>
    password: <pass>
    from_addr: <e-mail>
key_filename:
    name: priv_11
instances:
    key_name: qwerty
    tenant_id: e06a9c22d8154c64b9c98db92d49ab7d
